# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# postgres hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false