spring.application.name=task-tracker

# def profile for h2 base
spring.profiles.active=dev

# JWTs
app.jwt.secret=${JWT_SECRET:task-tracker-api-development-secret-very-very-big-secret-please-hire-me-asterbit}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}






